export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Dashboard } from "./Dashboard";
export { default as ApplyLoan } from "./ApplyLoan";
export { default as AdminPanel } from "./AdminPanel";
export { default as LoanDetail } from "./LoanDetail";
export { default as KYCSubmit } from "./KYCSubmit";
export { default as LenderReview } from "./LenderReview";
export { default as AuditLogs } from "./AuditLogs";